user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

#login:
#   path:   /login
#   defaults:  { _controller: UserBundle:Login:login }

api_login_check:
    path: /api/login_check

#logout:
#    path: /logout